name: CI
on:
  push: 
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
name: Checkout Repository
      uses: actions/checkout@v5

      
name: run a one-line script
      run: echo Hello World!
name: run a multi-line script
run: |
  echo More actions!
  echo skibidi!
