name: Main workflow
on: push

env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v4
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .

  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Checkout repository (with history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter/slim@v7   # <-- correct repo/org
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true

  Docker-image:
      runs-on: ubuntu-latest
      needs: [Build]
      permissions:
        packages: write
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show where the Dockerfile is
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -iname 'Dockerfile' -o -iname '*.Dockerfile' | sed 's/^/FOUND: /'

      - name: Build docker
        run: bash ci/build-docker.sh
          

      - name: Push docker
        run: bash ci/push-docker.sh

